peerplays-network/peerplays

libraries/chain/account_evaluator.cpp
libraries/chain/include/graphene/chain/account_object.hpp
libraries/chain/include/graphene/chain/config.hpp
tests/tests/voting_tests.cpp

Ported from bitshares: https://github.com/bitshares/bitshares-core/pull/1449
The new field `last_vote_time` in the statistics object will allow to have the date of the last voting activity of each account.
This can be used to fight voter apathy by alerting in the wallet to users that don't vote since some time.
So it can bee used standalone but it also serves as a part of bigger changes i am making to the voting system of peerplays.

add last_vote_time to account statistics

---

Dockerfile

This updates boost from 1.57.0 to 1.60.0 and also adds ntp to the docker build process.

Added ntp and upgraded boost version

---

libraries/net/CMakeLists.txt
libraries/wallet/CMakeLists.txt

This fixes the build issues encountered when running `cmake` in a different directory than the source directory, for example using the common
```
mkdir build && cd build && cmake ..
```

Fix out-of-source CMake builds

---

libraries/net/node.cpp

Backport Bitshares PR https://github.com/bitshares/bitshares-core/pull/1091
find() was being called 3 times on 2 different collections, when 1 call on each would suffice.

[GRPH-70] remove needless find()

---

tests/app/main.cpp

Fix for failed app_test. Can be used as a test for https://github.com/peerplays-network/peerplays/pull/92

[GRPH-71] Fix failed app_test

---

tests/tests/database_tests.cpp

Backport Bitshares https://github.com/bitshares/bitshares-core/pull/326

[GRPH-51] Created unit test for bitshares issue #325

---

libraries/chain/db_block.cpp
libraries/chain/db_update.cpp
libraries/chain/db_witness_schedule.cpp
libraries/chain/include/graphene/chain/database.hpp
tests/tests/block_tests.cpp

From https://github.com/bitshares/bitshares-core/pull/1087
Fixes database::update_global_dynamic_data to speed up counting missed blocks.
(This also fixes a minor issue with counting - the previous algorithm would skip missed blocks for the witness who signed the first block after the gap.)

Short-cut long sequences of missed blocks

---

libraries/app/database_api.cpp
libraries/db/include/graphene/db/index.hpp

Fixed errors while reading object_database were silently ignored, which could lead to an incomplete or inconsistent database after restart. Now, exceptions are no longer caught and will trigger application abort.

Grph 48 object database 18.04

---

libraries/app/api.cpp
libraries/plugins/account_history/account_history_plugin.cpp
tests/common/database_fixture.cpp
tests/tests/history_api_tests.cpp

A node with track-account configured has bigger history_object_id's (1.11.x) than nodes with default configuration values.
The problem was caused by using of use_next_id(). 
When creating new objects, old_index_next_ids will be updated in on_create(), when undoing, the value will be reverted to saved old id.
But in history plugin we didn't save old ids in old_index_next_ids, thus no reversion will be done when undoing.
Bitshares PR: https://github.com/bitshares/bitshares-core/pull/875

GRPH-90 Fix for history ID mismatch issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build_error.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

The Github issues needs better management. As a starting point, adding few templates.

Update issue templates

---

.gitlab-ci.yml
tests/cli/main.cpp

* updates the check-out commit for the `fc` submodule
* updates a single test file to the new API so that tests build successfully

Update the FC submodule with the changes for GRPH-4

---

libraries/app/CMakeLists.txt
libraries/app/application.cpp
libraries/app/config_util.cpp
libraries/app/include/graphene/app/application.hpp
libraries/app/include/graphene/app/config_util.hpp
libraries/plugins/delayed_node/delayed_node_plugin.cpp
programs/delayed_node/main.cpp
programs/witness_node/main.cpp

- Empty SON plugin is INACTIVE by default
- To enable it, add peerplays_sidechain to plugins section in
config file, or use --plugins command line option
- Plugin can work with or without witness

Part two of SON-83 - plugins option in command line and config file (for SONS-base branch only)

---

libraries/chain/account_object.cpp
libraries/chain/db_block.cpp
libraries/chain/include/graphene/chain/account_object.hpp

This PR includes small performance improvements:
- removed unnecessary hash calculation
- Efficient comparison  for set and map of account_object

GRPH-80 - minor performance improvement

---

libraries/wallet/wallet.cpp
tests/cli/main.cpp

Call the cli_wallet api with the params:
```{"id":"5665571840","jsonrpc":"2.0","method":"get_account_history","params":["alanguanwz9",1000]}```
The return result contains duplicate id : 1.11.323175501, 1.11.320758270
`./tests/cli_test -t account_history_pagination`

[GRPH-86] fix duplicate ops returned in get_account_history

---

libraries/chain/include/graphene/chain/config.hpp
libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp

Add chain extension parameter to set SON count
LLD at https://peerplays.atlassian.net/wiki/spaces/PIX/pages/333971489/SON+Objects+and+Operators

SON11 - Add chain extension parameter to set SON count

---

libraries/app/database_api.cpp
libraries/app/include/graphene/app/database_api.hpp
libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp

An API call that can return the total number of assets available. This will be used to get rid of loading assets on UI

[GRPH-111] Added get_asset_count API

---

libraries/chain/db_block.cpp

Backport BitShares PR https://github.com/bitshares/bitshares-core/pull/1247
This enhancement increases temporally undo db size for nested proposals if it is needed,  and than returns it back.
QA notes: to test this code you need to create the nested proposal with big enough nested authorities  required to sign this proposal ([see details here](https://dev.bitshares.works/en/master/knowledge_base/trn_proposed_transactions.html))

[GRPH-95] Enhancement for session undo storage

---

tests/app/main.cpp

Address issue https://github.com/peerplays-network/peerplays/issues/152
Looks like listening socket is closed in correct way and it is the OS issues,  so the best way I've found is to use random free port in tests.
QA notes: to check the fix is working start `tests/app_test` several times one after other.

Use random port numbers in app_test

---

libraries/chain/include/graphene/chain/proposal_object.hpp

The `fail_reason` was missing from `FC_REFLECT_DERIVED` for `proposal_object` class. Hence it wasn't returning while calling `get_object obj_id`

GRPH-79 Proposal Information Bug Fix

---

libraries/chain/include/graphene/chain/vesting_balance_evaluator.hpp
libraries/chain/vesting_balance_evaluator.cpp
libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp

Changes to have separate methods and single withdraw fee for multiple objects
Charge only single fee on withdrawing from multiple vest objects

Changes to have separate withdraw_vesting methods and single withdraw fee for multiple objects

---

libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp
tests/cli/main.cpp

Incorporated cli tests from bitshares and related bug fixes and/or enhancements.
**Here is the list of additional tests:**
- saving_keys_wallet_test
- cli_multisig_transaction
- cli_set_voting_proxy
- cli_cant_get_signers_from_modified_transaction
- cli_get_available_transaction_signers
- cli_get_signed_transaction_signers

[GRPH-3] Additional cli tests

---

libraries/wallet/wallet.cpp
tests/cli/main.cpp

Remove some code not needed and also added a simple delete test case to the framework. 
We were having an issue of segfault yesterday with the wallet delete command that was fixed by https://github.com/peerplays-network/peerplays/pull/177
We were having an issue in the chain_test son delete command that was fixed by: https://github.com/peerplays-network/peerplays/pull/176

remove not needed code form son cli wallet commands

---

libraries/chain/include/graphene/chain/config.hpp
libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
libraries/chain/include/graphene/chain/protocol/vesting.hpp
libraries/chain/include/graphene/chain/vesting_balance_object.hpp
libraries/chain/son_evaluator.cpp
libraries/chain/vesting_balance_evaluator.cpp
libraries/chain/vesting_balance_object.cpp
tests/tests/operation_tests.cpp
tests/tests/operation_tests2.cpp
tests/tests/son_operations_tests.cpp

This pull request brings the code already added into https://github.com/peerplays-network/peerplays/pull/144 in regards to the addition to a vesting balance policy for son member creation.
The number of conflicts after the merge of `develop` into `feature/SONs-base` were so many that we decided to just create a new pull.
This commits are following specs described at https://peerplays.atlassian.net/wiki/spaces/PIX/pages/335577138/SON+Claiming+Vesting+Amount
Please note that `feature/SONs-base` currently don't have any GPOS code on it. Some code like the vesting_balance_type field was introduced in that implementation so they had to be re implemented here. This will lead to some conflicts when GPOS gets merged here however the conflicts should be minimal.

Son vesting balance implementation

---

libraries/chain/include/graphene/chain/protocol/vesting.hpp
libraries/chain/vesting_balance_evaluator.cpp
libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp

**corrected/improved error messages on following cli wallet commands:**
- vote_for_witness
- withdraw_GPOS_vesting_balance
- withdraw_vesting
- vote_for_committee_member

[BLOCKBACK-162] Error message correction

---

libraries/chain/db_maint.cpp
libraries/chain/hardfork.d/GPOS.hf
tests/tests/gpos_tests.cpp

Eliminate time gap between two consecutive vesting periods

BLOCKBACK-164 Eliminate time gap between two consecutive vesting periods

---

libraries/chain/db_maint.cpp
tests/tests/gpos_tests.cpp

Fixed small bug and added test case

[BLOCKBACK-166] GPOS - dividend distribution for UIAs

---

libraries/chain/account_evaluator.cpp
tests/tests/gpos_tests.cpp

The `update_last_voting_time` is always `true` at every `account_update_operation`. This causes the date to be updated even if user didn't participated in the voting but just executed an update operation. It is also the cause of failure in `voting_tests`.
I think this is not the desired effect as the flag is false by default. This PR(specifically the first commit: https://github.com/peerplays-network/peerplays/commit/a80d25f9df1e720c1135cc9108325fb7ce8c8b94) attempts to fix that.

Fix update_last_voting_time flag

---

libraries/chain/db_maint.cpp
libraries/wallet/wallet.cpp
tests/tests/gpos_tests.cpp

On starting new vesting period, all votes become zero until someone votes, To avoid a situation of zero votes, changes done to roll in GPOS rules. The vesting factor will be 1 for whoever votes in 6th sub-period of last vesting period

BLOCKBACK- 174 Roll in GPOS votes from 6th sub-period 

---

libraries/chain/include/graphene/chain/protocol/son.hpp

The reason was incorrect `son_delete_operation` reflection: new field `payer` wasn't added to reflection scheme,  and it was the reason of the incorrect serialization.

[SON-142] Fix failed SON deletion CLI tests

---

libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp
tests/cli/son.cpp

I've made it similar to `create_vesting_balance` call in GPOS branch and I have changed vesting_type argument as @oxarbitrage has described in  https://github.com/peerplays-network/peerplays/pull/179#discussion_r337750987 . 
Now cli wallet call should look like 
```
unlocked >>> create_vesting_balance nathan 50 TEST son true
```
@oxarbitrage, take a look, please,  is it what you mean?

[SON-160] Fix create_vesting wallet_api call

---

libraries/chain/protocol/account.cpp
libraries/wallet/wallet.cpp
tests/cli/son.cpp

- accepted and rejected SONs lists can't be empty simultaneously;
- fix incorrect error message for wrong accepted SON;
- check number of SONs against votes number in account_object (similar to witness and committee member number);

[SON-113] Fix several issues in update_son_votes call in wallet_api 

---

libraries/chain/account_evaluator.cpp
libraries/chain/account_object.cpp
libraries/chain/db_balance.cpp
libraries/chain/db_debug.cpp
libraries/chain/db_getter.cpp
libraries/chain/db_init.cpp
libraries/chain/db_maint.cpp
libraries/chain/include/graphene/chain/account_object.hpp
libraries/chain/include/graphene/chain/config.hpp
libraries/chain/include/graphene/chain/database.hpp
libraries/chain/include/graphene/chain/protocol/account.hpp
tests/common/database_fixture.cpp
tests/tests/voting_tests.cpp

This fix is related to account maintenance performance improvement.
- Avoid using new db object (db()) every time
- Avoid passing all local object to lambda functions
- Improved account_statistics_object class
- Efficient indexing by account_stats_multi_index_type
- account_balance_object indexing by maintenance_flag
Testing steps:
- Run witness_node of existing codebase and sync the existing chain (should have around 27,000,000 blocks)
- Get this line from log "Done reindexing, elapsed time: 1.40301600000000004 sec"
- Run witness_node of with this patch and sync the existing chain (Number of blocks should be same as above)
- Get the same line from log "Done reindexing, elapsed time: 1.33971499999999999 sec"
Reference: https://github.com/bitshares/bitshares-core/pull/1085/

Improve account maintenance performance

---

libraries/net/node.cpp

The peer is an attacker or buggy, which means the item_hashes_received is
not correct.
Move the check before updating items ids to save some time in this case.
Resolves issue https://github.com/peerplays-network/peerplays/issues/148
Backport of the Bitshares PR https://github.com/bitshares/bitshares-core/pull/1007

[GRPH-114] Check the attacker/buggy client before updating items ids

---

libraries/chain/db_init.cpp
libraries/db/include/graphene/db/index.hpp

The primary issue causing the betting test fail is due to the new `insert` function added in `class primary_index` file `index.hpp`. 
```
virtual const object& insert( object&& obj )override
{
const auto& res = DerivedIndex::insert(std::move(obj));
for( const auto& item : _sindex )
item->object_inserted( res );
on_add(res);
return res;
}
```
This function was added to fix SON tests (SON-142) #176 . The fix provided was correct for SON test. But on the other hand betting tests are failing with this change.
The reason behind it is the `secondary_index`. 
```
for( const auto& item : _sindex )
item->object_inserted( res );
```
As shown in the above snippet, It executes the `object_inserted` function of `secondary_index`. There are various `secondary_index` that have been added for betting …

Fixed betting tests

---

libraries/chain/account_object.cpp
libraries/chain/asset_evaluator.cpp
libraries/chain/asset_object.cpp
libraries/chain/db_balance.cpp
libraries/chain/db_block.cpp
libraries/chain/db_getter.cpp
libraries/chain/db_init.cpp
libraries/chain/db_maint.cpp
libraries/chain/db_management.cpp
libraries/chain/db_market.cpp
libraries/chain/db_update.cpp
libraries/chain/db_witness_schedule.cpp
libraries/chain/include/graphene/chain/asset_object.hpp
libraries/chain/include/graphene/chain/database.hpp
libraries/chain/protocol/asset.cpp
libraries/chain/worker_evaluator.cpp

Backport of the Bitshares PR https://github.com/bitshares/bitshares-core/pull/1180.
It adds several optimization:
- cache several objects as class members instead of recreation every time we need them;
- optimize `update_expired_feeds` with tracking of the expired rates;
- a set of minor optimizations;

[GRPH-81] Different performance optimization

---

tests/tests/history_api_tests.cpp

Added unit test for `get_account_history_operations`. It should return empty result when the account has not executed the specified operation

Added unit test for empty account history

---

libraries/app/CMakeLists.txt
libraries/app/config_util.cpp
libraries/app/include/graphene/app/config_util.hpp
programs/witness_node/main.cpp

When we specify `witness-id` or `private-key` multiple times in `config.ini` it is giving this warning:
`Error parsing logging config from config file ~/data2/my-blockprod/config.ini, using default config` 
The boost call `boost::property_tree::ini_parser::read_ini` will fail if it found multiple entries of same parameters.
Just like Bitshares,  Creating new config `logging.ini` for logging with more logging options.

[GRPH-150] P2P Log files are not created

---

libraries/chain/committee_member_evaluator.cpp
libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
libraries/chain/proposal_evaluator.cpp

The `extension` section of chain parameters remains empty until the committee proposal is submitted. This is fixed by setting the default values of all extensions parameters.
Also, removed the old hardfork betting checks which were required to be removed after the hf.

[BLOCKBACK-182] set extensions default values

---

libraries/chain/db_block.cpp
libraries/chain/proposal_object.cpp

**Fixed issue:** 
chainparameters are not getting updated with committee proposal
**Steps for QA:**
- Create Proposal
`propose_parameter_change nathan "2019-12-05T12:40:00" {"extensions" : {"gpos_period":7200, "gpos_subperiod": 1200}} true`
- Approve Proposal
`approve_proposal nathan "1.10.12" {"active_approvals_to_add" : ["init0", "init1", "init2", "init3", "init4", "init5", "init6", "init7"]} true`
Here,  `1.10.12` is Proposal Id

[GRPH-166] Fixed chainparameter update proposal issue

---

libraries/app/database_api.cpp
libraries/app/include/graphene/app/database_api.hpp
libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
libraries/chain/include/graphene/chain/protocol/vesting.hpp
libraries/chain/vesting_balance_evaluator.cpp
libraries/wallet/wallet.cpp
tests/tests/gpos_tests.cpp

Move GPOS withdraw logic to evaluator to have single transaction(also single fee) from frontend
Update `get_gpos_info` API to list 1) User Vested Balance 2) Allowed Withdraw Amount
Update default chain parameter info to list GPOS period start on extension parameters(get_global_properties command from cli_wallet would display all chain parameters )

BLOCKBACK-186 fix: GPOS

---

libraries/chain/account_evaluator.cpp
libraries/chain/db_maint.cpp
tests/tests/gpos_tests.cpp

Votes consideration on GPOS activation for the first half of first GPOS sub-period. This piece of code added to avoid zero votes on activation.

BLOCKBACK-183 GPOS: Votes consideration on GPOS activation

---

libraries/chain/vesting_balance_evaluator.cpp
tests/tests/gpos_tests.cpp

Fixed GPOS withdraw vesting issue

[BLOCKBACK-186] Withdraw vesting bug fix

---

.gitmodules
libraries/chain/hardfork.d/GPOS.hf
libraries/chain/proposal_object.cpp

Update hardfork date for TESTNET, sync fc module and update logs level msg

Update hardfork date for TESTNET, sync fc module and update logs

---

libraries/chain/include/graphene/chain/protocol/vesting.hpp
libraries/chain/vesting_balance_evaluator.cpp
libraries/wallet/wallet.cpp
tests/tests/gpos_tests.cpp

To resolve sync issue,
balance type has been removed from vesting withdraw operation and GPOS type validation done on vesting balance object.

GPOS-1, Testnet sync issue fix

---

libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp

Sidechain Plugin Code to report SON Down
Sidechain plugin code to approve the SON Down Proposal.
On every block received the scheduled SON will check for other down SONs.
On every new object created in the database, active SON will check if approval is required for SON related proposals.

SON212-SON213 - Add Sidechain Plugin Code to report and approve SON Down proposal

---

libraries/chain/son_evaluator.cpp
libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
tests/tests/son_operations_tests.cpp

SON Maintenance and Heartbeat transition changes
When a SON which is in maintenance sends a heartbeat, the son evaluator should check if the SON is present in the list of active sons stored in chain_parameters.
If it is present we should move it to the active state otherwise we should move it to the inactive state.

SON217 - SON Maintenance,Heartbeat state transition changes

---

libraries/app/impacted.cpp
libraries/chain/db_init.cpp
libraries/chain/db_maint.cpp
libraries/chain/db_notify.cpp
libraries/chain/include/graphene/chain/protocol/operations.hpp
libraries/chain/include/graphene/chain/protocol/son.hpp
libraries/chain/include/graphene/chain/son_evaluator.hpp
libraries/chain/include/graphene/chain/son_object.hpp
libraries/chain/proposal_evaluator.cpp
libraries/chain/son_evaluator.cpp
libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp
tests/cli/son.cpp
tests/tests/son_operations_tests.cpp

Also fixes a bug with going SON to active mode. Adds `start_son_maintenance` and `stop_son_maintenance` calls to CLI wallet and tests for this functions.

[SON-202] Implement cli_wallet commands for maintenance mode

---

tests/tests/son_operations_tests.cpp

Unit failing because of transaction expiry value.

SON199 - Fix Unit Test Failure

---

libraries/wallet/wallet.cpp

Keys mapping missing from wallet data

SON165 - Keys mapping missing from wallet data

---

libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
libraries/plugins/bookie/bookie_plugin.cpp
libraries/wallet/wallet.cpp

Bring in updates from mainnet branch(mainnet sync issue fixes)

Bring in updates from mainnet branch

---

libraries/chain/db_block.cpp
libraries/chain/db_witness_schedule.cpp
libraries/chain/include/graphene/chain/database.hpp
libraries/chain/include/graphene/chain/fork_database.hpp

Right now we only check if a received block is linkable to an existing block in fork_db but do no other checks. If the network code also doesn't reject multiple blocks at the same block height from the same node, it opens itself up to an easy DOS attack.
Rather than relying only on the network code to protect against such attacks, we should do some light validation of the received blocks (particularly enough to check that it was correctly signed by an active producer from the perspective of that block) before including it into the fork_db.

[GRPH-160] check witness signature before adding block to fork db

---

libraries/plugins/peerplays_sidechain/CMakeLists.txt
libraries/plugins/peerplays_sidechain/bitcoin_utils.cpp
libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/bitcoin_utils.hpp
libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/defs.hpp
libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler_bitcoin.hpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp
tests/peerplays_sidechain/bitcoin_utils_test.cpp

Adds functionality required to transfer funds from old Primary Wallet (P2SH on the base of the custom redeem script) to new Primary Wallet.
Primary wallet address is added to bitcoin wallet with `importaddress` call, `list_unspent` allows to get inputs and send them to `createrawtransaction`, that can be signed with custom code and published after that,  the process described in unit tests in bitcoin_utils_tests.cpp
I hasn't implemented full primary wallet recreation with this functionality to have ability to merge it faster,  I'll add separate PR after this one will be merged.

[SON-209] Create P2SH address with custom redeemScript

---

libraries/chain/db_block.cpp

Getting wrong slot to fetch witness signature. This has been fixed to verify the witness signature before pushing the block. This is a fix to GRPH-160(#PR 226)

fix verify witness signature method

---

libraries/chain/db_block.cpp
libraries/chain/db_getter.cpp
libraries/chain/db_init.cpp
libraries/chain/include/graphene/chain/config.hpp
libraries/chain/include/graphene/chain/database.hpp
libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
libraries/chain/son_evaluator.cpp
libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
tests/tests/son_operations_tests.cpp

1. Making deregistration clean by moving it to plugin from witness.
2. Addition of chain extension parameters to configure deregistration, heartbeat frequency, report. downtime.
3. Modification of tests.

SON269 - Move SON deregistration to Plugin from witness

---

libraries/app/application.cpp
tests/app/main.cpp
tests/cli/main.cpp

On bringing new elasticsearch plugin changes, witness should be able to run default plugins without plugin options. At the same time, witness should run other mandatory plugins like "witness" if only "elasticsearch" and "es-objects" passes under plugin options.
Changes done to implement the above changes.
Note: we can't enable both account_history and elasticsearch plugins at the same time

Enable mandatory plugins to have smooth transition for next release

---

libraries/chain/include/graphene/chain/protocol/son_wallet_deposit.hpp
libraries/chain/include/graphene/chain/protocol/son_wallet_withdraw.hpp
libraries/chain/include/graphene/chain/son_object.hpp
libraries/chain/include/graphene/chain/son_wallet_deposit_object.hpp
libraries/chain/include/graphene/chain/son_wallet_withdraw_object.hpp
libraries/chain/son_wallet_deposit_evaluator.cpp
libraries/chain/son_wallet_withdraw_evaluator.cpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler.cpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp

- Deposit and Withdrawal object extended to contain expected
and received transaction reports from SON network
- SON statistic object extended to contain total number of
sidechain transactions reported by SON network when SON was
active and number of transactions reported by single SON when
he was active
- Code formatting

Add SON statistic for tracking reported sidechain transactions

---

libraries/chain/include/graphene/chain/global_property_object.hpp
libraries/chain/son_evaluator.cpp

1. Added missing serializations
2. Updating statistics in heartbeat evaluator temporarily to enable testing.
3. Tested end to end and tallied the budget/current supply

[SON-24] - SON Rewards missing serialisations and end to end testing capability

---

libraries/wallet/include/graphene/wallet/wallet.hpp
libraries/wallet/wallet.cpp

Adds new `try_create_son` call to `wallet_api` that doesn't require explicit vesting balance object params

[SON-311] Son creation with cli wallet refactoring

---

.gitlab-ci.yml
tests/cli/son.cpp

Very clean build on Gitlab
Fix failing son test, fix data types and check condition

[SON-332] Check gitlab building process for dirty build

---

libraries/chain/db_maint.cpp

The reason for failing unit test case fatal error: in "dividend_tests/test_update_dividend_interval": unknown type is, missing the stats parameter in creating son-account. It has be fixed in son-account creation.
SON-329 fix

update son-account parameters

---

libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler.hpp
libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler_bitcoin.hpp
libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler_peerplays.hpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler.cpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp
libraries/plugins/peerplays_sidechain/sidechain_net_handler_peerplays.cpp

- Fixed
- Unused parameters removed

[SON-348] Transaction hash not saved after Bitcoin transaction is sent

---

libraries/chain/asset_object.cpp
libraries/chain/hardfork.d/5050-1.hf
libraries/chain/include/graphene/chain/asset_object.hpp
libraries/chain/include/graphene/chain/protocol/lottery_ops.hpp
tests/tests/lottery_tests.cpp

This PR is to introduce the winner_ticket_id changes to sweeps dApp

5050 winner id changes

---

libraries/chain/db_maint.cpp
libraries/chain/hardfork.d/GPOS2.hf

- Rolling period not aligning with maintenance block if there are missing blocks at GPOS period end.
- HF epoch time to be adjusted separately for testnet and master branches.
- This should fix assert failures happening during maintenance.

GPOS2 HF - Handle rolling period on missing blocks

---

libraries/chain/db_block.cpp
libraries/chain/db_notify.cpp
libraries/chain/hardfork.d/CORE_210.hf
libraries/chain/include/graphene/chain/impacted.hpp
libraries/chain/include/graphene/chain/protocol/custom.hpp
libraries/chain/include/graphene/chain/protocol/operations.hpp
libraries/chain/include/graphene/chain/protocol/transaction.hpp
libraries/chain/proposal_evaluator.cpp
libraries/chain/proposal_object.cpp
libraries/chain/protocol/operations.cpp
libraries/chain/protocol/transaction.cpp
libraries/plugins/account_history/account_history_plugin.cpp
libraries/plugins/elasticsearch/elasticsearch_plugin.cpp
tests/tests/authority_tests.cpp

This is an old issue where the custom_operation's required_authorities field was not checked when determining the required authorities for the operation/transaction. This adds the necessary checks, but it's a hardfork so there are hardfork guards as well.

Fix for custom operation authority checking (BTS Issue #210)

---

libraries/wallet/wallet.cpp

This will prevent errors when trying to buy/sell assets with precision less than 6.

Hotfix: Fix double to string conversion in buy/sell cli wallet commands

---

libraries/chain/db_management.cpp

Start replay with
witness_node --replay-blockchain
Interrupt it with CTRL+C, and continue at last flush point, without --replay-blockchain parameter
witness_node

Flush chain database during replay
