- libraries/chain/include/graphene/chain/config.hpp
- libraries/chain/include/graphene/chain/event_group_object.hpp
- libraries/chain/include/graphene/chain/event_object.hpp
update db_version for replay and remove duplicate include files
> update db_version for replay and remove duplicate include files

- genesis.json
- libraries/app/database_api.cpp
- libraries/app/include/graphene/app/database_api.hpp
- libraries/chain/db_maint.cpp
- libraries/chain/hardfork.d/GPOS.hf
- libraries/chain/include/graphene/chain/config.hpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
- libraries/chain/include/graphene/chain/protocol/vesting.hpp
- libraries/chain/include/graphene/chain/vesting_balance_object.hpp
- libraries/chain/proposal_evaluator.cpp
- libraries/chain/vesting_balance_evaluator.cpp
- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
- tests/tests/gpos_tests.cpp
This pull request is not the final version and should not be merged without at least the following TBD:
Function `calculate_vesting_factor` is a key component of the new protocol, however current implementation is buggy as described in some of the test cases. 
Function IMO is more complicated than it should be and a redesign of it to get the same results in a more consistent way should be implemented.
Refer to the next document explain more about the protocol and implementation: https://github.com/oxarbitrage/documentation/tree/master/peerplays
> GPOS protocol

- tests/app/main.cpp
- tests/betting/betting_tests.cpp
- tests/common/genesis_file_util.hpp
- tests/intense/block_tests.cpp
- tests/tests/block_tests.cpp
- tests/tests/dividend_tests.cpp
- tests/tests/fee_tests.cpp
- tests/tests/gpos_tests.cpp
- tests/tests/network_broadcast_api_tests.cpp
- tests/tests/operation_tests.cpp
- tests/tests/operation_tests2.cpp
PR to merge Unit test case fixes into beatrice
> Unit test case fixes

- libraries/chain/db_block.cpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/include/graphene/chain/operation_history_object.hpp
Fix to display common virtual_op number across all nodes
> virtual-op-fix for deterministic virtual_op number

- .gitmodules
- libraries/chain/hardfork.d/CORE-429.hf
- libraries/chain/hardfork.d/SWEEPS.hf
- libraries/chain/include/graphene/chain/config.hpp
Update hardfork date for 18.04 upgrade + 50/50 dApp release
Point fc path to peerplays-network
> Hardfork 50/50

- libraries/app/application.cpp
- libraries/plugins/delayed_node/delayed_node_plugin.cpp
- programs/cli_wallet/main.cpp
Related FC PR has been raised temporarily at, 
https://github.com/satyakoneru/peerplays-fc/pull/1/files
Fix is one of the commits in the below PR on bit-shares,
https://github.com/bitshares/bitshares-core/pull/1695/files
> GRPH-4-CliWallet_crash_ctrlD

- libraries/wallet/wallet.cpp
Don't allow to vote when the vesting balance is 0
> issue - 157: Don't allow to vote when the vesting balance is 0

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/config.hpp
- libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
- libraries/chain/include/graphene/chain/protocol/vesting.hpp
- libraries/chain/include/graphene/chain/vesting_balance_object.hpp
- libraries/chain/proposal_evaluator.cpp
- libraries/chain/vesting_balance_evaluator.cpp
- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
Below are the changes done to fix issue 153(withdraw_vesting functionality is not working)
1. Changes done in the core method to distinguish between normal and GPOS vesting and iterate through all vesting balances to allow withdraw.
2. Vesting lock in period introduced(currently set to 30 days) based on Jonathan inputs.
3. Previous vesting balance changed from "Unspecified" to "Normal"
> Issue Blockback 153 fix

- Dockerfile
- tests/tests/operation_tests.cpp
- tests/tests/operation_tests2.cpp
> fixing build errors

- libraries/app/database_api.cpp
Return only non-zero vesting balance objects
> 163-fix, Return only non-zero vesting balances

- libraries/app/application.cpp
- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/database.hpp
- tests/common/database_fixture.cpp
- tests/tests/voting_tests.cpp
Reference: https://github.com/bitshares/bitshares-core/commit/c2eb20e6a458530a377710de14b52ec62ca3d008
> [GRPH-106] Added voting tests

- tests/cli/main.cpp
> [SON-110] get_son cli test

- libraries/db/include/graphene/db/index.hpp
- tests/common/database_fixture.cpp
Fixes failed `affiliate_tests` and `delete_son_test`
QA Notes: `tests/chain_test` working correctly
> [SON-142] Fix the failed tests in SONs-base

- libraries/net/node.cpp
- libraries/net/peer_connection.cpp
Adjust the log level for few p2p logs.
> [GRPH-127] Adjust p2p log level

- .gitmodules
FC repository is changed to peerplays/peerplays-fc
Point to fc commit hash 6096e94 [latest-fc branch]
> [GRPH-131] Updated FC repository to peerplays-network/peerplays-fc

- libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
- tests/tests/son_operations_tests.cpp
As reported in https://github.com/peerplays-network/peerplays/pull/179#issuecomment-544564173 and by other channels. 
There is an error in the build probably caused by a wrong conflict resolution. This PR fixes it.
> fix build error

- Doxyfile
Updated project name in Doxyfile
To Generate Documents:
- Go to project directory:`cd peerplays`
- Run `doxygen Doxyfile`
Open `peerplays/doxygen/html/index.html` file in browser
> [GRPH-112] Doxyfile updates

- libraries/chain/db_block.cpp
- libraries/chain/db_getter.cpp
- libraries/chain/db_init.cpp
- libraries/chain/include/graphene/chain/config.hpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/include/graphene/chain/proposal_evaluator.hpp
- libraries/chain/include/graphene/chain/protocol/son.hpp
- libraries/chain/include/graphene/chain/protocol/types.hpp
- libraries/chain/include/graphene/chain/son_object.hpp
- libraries/chain/include/graphene/chain/son_proposal_object.hpp
- libraries/chain/proposal_evaluator.cpp
- libraries/chain/son_evaluator.cpp
- libraries/wallet/wallet.cpp
- tests/tests/son_operations_tests.cpp
PR for,
Witness Proposal for SON related activities
Adding a new object/index to keep track of SON related proposals that can be used for future SON related proposals.
Corrected the Vesting period after de-reg to 2 days
Added witness proposal tests.
> SON126 - Witness Proposals to deregister SONs

- libraries/chain/db_maint.cpp
- tests/tests/gpos_tests.cpp
Fixed vesting factor calculation issue in case of proxy voting. 
As per @pbattu123 instruction, I'm raising this PR to merge it in `qa_gpos_18.04` branch.
> [BLOCKBACK-165] Fixed GPOS vesting factor issue when proxy is set

- libraries/wallet/wallet.cpp
Small change related to SYMBOL in the error message.
> [BLOCKBACK-162] Added token symbol name in error messages

- libraries/chain/account_evaluator.cpp
- libraries/chain/include/graphene/chain/protocol/account.hpp
- libraries/wallet/wallet.cpp
Fixed last voting time update issue
Cherry-picked `get_account` fix from `develop`
> [Blockback 155] GPOS - Multiple issues with vote_for_witness

- libraries/chain/vesting_balance_evaluator.cpp
- libraries/wallet/wallet.cpp
Fixed spelling mistake in an error message
> [BLOCKBACK-162] Fixed spelling issue in error message

- libraries/app/application.cpp
- libraries/plugins/delayed_node/delayed_node_plugin.cpp
- programs/cli_wallet/main.cpp
- tests/cli/main.cpp
Related FC Change, 
https://github.com/peerplays-network/peerplays-fc/pull/7
Both should be taken to avoid compilation errors.
> GRPH134- High CPU Issue, websocket changes

- .gitmodules
update submodule branch(path) to refer to the latest commit on latest-fc branch
> update submodule branch to refer to the latest commit on latest-fc branch

- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
- tests/cli/son.cpp
Adds `list_active_sons` call to wallet API and the unit test for it.
> [SON-150] list_active_sons wallet_api call 

- libraries/app/database_api.cpp
- libraries/chain/db_maint.cpp
- libraries/chain/hardfork.d/GPOS.hf
- libraries/wallet/wallet.cpp
Update GPOS hardfork date and don't allow GPOS features before hardfork time
> BLOCKBACK-181 Update GPOS hardfork date and don't allow GPOS features before hardfork time

- libraries/chain/vesting_balance_evaluator.cpp
- libraries/wallet/wallet.cpp
Withdrawal issue with GPOS balance. Fix for BLOCKBACK-177
> issue with withdrawl

- libraries/app/api.cpp
- libraries/app/database_api.cpp
- libraries/app/include/graphene/app/api.hpp
- libraries/app/include/graphene/app/database_api.hpp
- libraries/wallet/wallet.cpp
- tests/tests/history_api_tests.cpp
- tests/tests/voting_tests.cpp
- Account Name or ID support in all API calls
- Asset ID or Symbol support in all API calls
> [GRPH-152] Allow APIs to be called by account/asset name and id

- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
bit-shares fix at,
https://github.com/bitshares/bitshares-core/pull/1104
Related FC PR raised temporarily at,
https://github.com/satyakoneru/peerplays-fc/pull/1
> GRPH-46-Quit_command_cliwallet

- libraries/chain/son_evaluator.cpp
- tests/CMakeLists.txt
- tests/app/main.cpp
> [SON-199] Fix unit tests

- libraries/app/impacted.cpp
- libraries/chain/db_init.cpp
- libraries/chain/db_notify.cpp
- libraries/chain/include/graphene/chain/protocol/operations.hpp
- libraries/chain/include/graphene/chain/protocol/son.hpp
- libraries/chain/include/graphene/chain/son_evaluator.hpp
- libraries/chain/include/graphene/chain/son_object.hpp
- libraries/chain/proposal_evaluator.cpp
- libraries/chain/son_evaluator.cpp
- tests/tests/son_operations_tests.cpp
SON Maintenance and Heartbeats
Tests are on the way and will be updated in the same PR.
> SON193-SON200- SON Heartbeats and maintenance mode changes

- libraries/chain/hardfork.d/GPOS.hf
Set hardfork date to Jan5th on TESTNET
> Set hardfork date to Jan5th on TESTNET

- libraries/chain/include/graphene/chain/son_object.hpp
- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/peerplays_sidechain_plugin.hpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
SON Heartbeats Plugin Changes
Serialization changes for son stats object
Stub-Tested the changes on private-testnet
> SON206 - Plugin SON Heartbeat changes

- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
> SON212-SON213 - Fix Build Error

- .gitlab-ci.yml
Fixes the CI build step regarding the FC library for the SONs-base and related branches.
> Updated gitlab CI to sync submodules

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/son_object.hpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
1. Crash Fix - P2P network not ready to send transactions from the plugin.
2. Proper serialization of son_object.
3. Reset the consensus account auths before modifying.
4. Plugin Code Reorg and additional logging.
> SON206_Plugin_CrashFix_Reorg - Plugin Changes

- libraries/chain/db_getter.cpp
- libraries/chain/db_update.cpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/include/graphene/chain/proposal_evaluator.hpp
- libraries/chain/include/graphene/chain/son_proposal_object.hpp
- libraries/chain/proposal_evaluator.cpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
Check for duplicate proposal creation and proposal approval from DB.
> SON232 - Avoid duplicate proposals from sidechain plugin

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/son_evaluator.cpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
Provide correct downtime metrics to the user
> SON233 - Provide correct downtime metrics to user

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/son_object.hpp
- libraries/chain/son_evaluator.cpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
- tests/cli/son.cpp
- tests/tests/son_operations_tests.cpp
Request maintenance wallet commands
CLI and Operations Tests
> SON214 - Request maintenance wallet commands

- libraries/wallet/wallet.cpp
Avoid directly overwriting wallet file on exit
> [GRPH-169] Avoid directly overwriting wallet file on exit 

- libraries/net/include/graphene/net/peer_connection.hpp
- libraries/net/message_oriented_connection.cpp
Reference: https://github.com/bitshares/bitshares-core/pull/2002/commits/eb9dc04c620a0827f11b547d7a37907ba8a00f68
> Replace verify_no_send_in_progress with no_parallel_execution_guard

- tests/app/main.cpp
- tests/common/database_fixture.cpp
- tests/tests/block_tests.cpp
To fix unit test failures with that pop-up with recent PR merges
> Fix unit test failures

- libraries/plugins/peerplays_sidechain/bitcoin_utils.cpp
- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/bitcoin_utils.hpp
- tests/peerplays_sidechain/bitcoin_utils_test.cpp
Addition to https://github.com/peerplays-network/peerplays/pull/271
> Adds ability to gather SONs signatures for PW tx without partial signing

- libraries/plugins/snapshot/CMakeLists.txt
- programs/witness_node/CMakeLists.txt
- programs/witness_node/main.cpp
Enable snapshot plugin feature
> enable snapshot plugin

- libraries/plugins/elasticsearch/elasticsearch_plugin.cpp
To fix minor issue in fetching size
> ES update1

- libraries/chain/db_init.cpp
- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
SON Down proposal is broken after latest merges, proper account auth not sent in proposals.
> SON200 - SON Down proposal broken after latest merges

- libraries/chain/include/graphene/chain/protocol/son.hpp
- libraries/chain/son_evaluator.cpp
- libraries/wallet/include/graphene/wallet/wallet.hpp
- libraries/wallet/wallet.cpp
- tests/cli/son.cpp
- tests/tests/son_operations_tests.cpp
1. Make maintenance wallet commands more intuitive
2. Test modifications
> SON202 - Maintenance improvements

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/config.hpp
- libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp
1. Crash fix
2. Chain parameter for SON Rewards pay frequency
> SON275 - ZMQ Crash on application exit

- libraries/chain/db_getter.cpp
- libraries/chain/db_maint.cpp
- libraries/chain/db_update.cpp
- libraries/chain/include/graphene/chain/database.hpp
- libraries/chain/son_evaluator.cpp
1. Fix proposal Exceptions
2. Some code reorg
> SON276 - Fix SON proposal exceptions - I

- libraries/plugins/peerplays_sidechain/peerplays_sidechain_plugin.cpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler.cpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler_peerplays.cpp
Issue BTC asset on deposit,  burn it on wothdraw
> [SON-305, SON-308, SON-310] Use BTC asset in bitcoin deposits and withdraws

- libraries/chain/asset_object.cpp
- libraries/chain/hardfork.d/5050-1.hf
- libraries/chain/include/graphene/chain/asset_object.hpp
- libraries/chain/include/graphene/chain/protocol/lottery_ops.hpp
- tests/tests/lottery_tests.cpp
Feature/nh5050 winner_ticket_id changes
> Feature/nh5050 winner_ticket_id changes

- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler.hpp
- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/sidechain_net_handler_bitcoin.hpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler.cpp
- libraries/plugins/peerplays_sidechain/sidechain_net_handler_bitcoin.cpp
- libraries/wallet/CMakeLists.txt
- tests/CMakeLists.txt
- tests/cli/son.cpp
* Added checks for existing proposal in proposal indec
* Unused dependencies on peerplays_sidechain removed
> [SON-353] Refactor PW processing, PW transfer fixed

- libraries/plugins/peerplays_sidechain/bitcoin/bitcoin_address.cpp
- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/bitcoin/bitcoin_address.hpp
- libraries/plugins/peerplays_sidechain/include/graphene/peerplays_sidechain/bitcoin/bitcoin_script.hpp
- tests/peerplays_sidechain/bitcoin_sign_tests.cpp
User can sign refund tx only after the time given in address ctor.
> [SON-135] Add timelock to user deposit address

- libraries/chain/db_maint.cpp
- libraries/chain/include/graphene/chain/database.hpp
1. Implementation of weighted son rewards.
2. Making son-account ownership equal-weighted.
> [SON-314] - Weighted Rewards and equal weighted son-account

- libraries/chain/asset_object.cpp
https://github.com/peerplays-network/peerplays/pull/363
> Mainnet chain halt 5050 Issue
